// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/group": {
            "post": {
                "description": "Create a specific group and not consume any message.",
                "consumes": [
                    "application/json"
                ],
                "summary": "Create group",
                "parameters": [
                    {
                        "description": "topic and group_id",
                        "name": "payload",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_server.GroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.APIRespond"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.APIRespond"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_server.APIRespond"
                        }
                    }
                }
            }
        },
        "/v1/publish": {
            "post": {
                "description": "Publish message(s) to kafka with topic and partition(optional)",
                "consumes": [
                    "application/json"
                ],
                "summary": "Publish message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "topic name",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "specific partition number",
                        "name": "partition",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "key",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "raw body",
                        "name": "raw",
                        "in": "query"
                    },
                    {
                        "description": "send key values",
                        "name": "payload",
                        "in": "body",
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.APIRespond"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.APIRespond"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_server.APIRespond"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_server.APIRespond": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_server.GroupRequest": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "",
	Description:      "github.com/worldline-go/molen",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
